spring.application.name=TodoListApi

spring.datasource.url=jdbc:sqlserver://SERVER_IP:1433;databaseName=DATABASE_NAME;encrypt=true;trustServerCertificate=true;
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=USERNAME
spring.datasource.password=PASSWORD

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=9000

server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=PASSWORD
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=springboot
